// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/erupshis/yugpa_test/internal/agent/dialer (interfaces: BaseDialer)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	messages "github.com/erupshis/yugpa_test/internal/messages"
	gomock "github.com/golang/mock/gomock"
)

// MockBaseDialer is a mock of BaseDialer interface.
type MockBaseDialer struct {
	ctrl     *gomock.Controller
	recorder *MockBaseDialerMockRecorder
}

// MockBaseDialerMockRecorder is the mock recorder for MockBaseDialer.
type MockBaseDialerMockRecorder struct {
	mock *MockBaseDialer
}

// NewMockBaseDialer creates a new mock instance.
func NewMockBaseDialer(ctrl *gomock.Controller) *MockBaseDialer {
	mock := &MockBaseDialer{ctrl: ctrl}
	mock.recorder = &MockBaseDialerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaseDialer) EXPECT() *MockBaseDialerMockRecorder {
	return m.recorder
}

// MakeRequestToServer mocks base method.
func (m *MockBaseDialer) MakeRequestToServer(arg0 context.Context, arg1 *messages.Request) (*messages.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MakeRequestToServer", arg0, arg1)
	ret0, _ := ret[0].(*messages.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeRequestToServer indicates an expected call of MakeRequestToServer.
func (mr *MockBaseDialerMockRecorder) MakeRequestToServer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeRequestToServer", reflect.TypeOf((*MockBaseDialer)(nil).MakeRequestToServer), arg0, arg1)
}
